### ISSUE TITLE
Problems with the use of the MCP in Docker

### ISSUE THREAD

**Issue by vk2r** [nic01asFr/mcp-server-grist#3]
I have tried to install the MCP using Docker. However, it does not work correctly. I have tried to configure it together with the official Grist container, but there are problems.

Could you give me a hand?

```yml
services:
  grist:
    image: gristlabs/grist:latest
    container_name: grist
    env_file: .env
    environment:
      - APP_DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
    volumes:
      - grist_data:/persist
    ports:
      - 8484:8484
    depends_on:
      grist-db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - grist-net

  grist-db:
    image: postgres:16-alpine
    container_name: grist-db
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - grist-net

  grist-mcp:
    container_name: grist-mcp
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:	
      - grist
      - grist-db
    networks:
      - grist-net

volumes:
  grist_data:
  pg_data:

networks:
  grist-net:
    driver: bridge
```

These are the logs:
```
grist-mcp  | 2025-06-04 18:21:02,621 - grist_mcp_server - INFO - Starting Grist MCP Server v0.1.0
grist-mcp  | 2025-06-04 18:21:02,622 - grist_mcp_server - WARNING - Module d'outils supplémentaires non trouvé: No module named 'grist_tools_integration'
grist-mcp  | 2025-06-04 18:21:02,622 - grist_mcp_server - INFO - Environment configuration: {'GRIST_API_KEY': '123123', 'GRIST_API_URL': '', 'GRIST_API_HOST': 'grist:8484/api', 'LOG_LEVEL': 'ALL'}
grist-mcp  | 2025-06-04 18:21:02,622 - grist_mcp_server - WARNING - Module d'outils supplémentaires non disponible: No module named 'grist_tools_integration'
grist-mcp  | 2025-06-04 18:21:02,622 - grist_mcp_server - INFO - Successfully initialized Grist client with URL: https://grist:8484/api
grist-mcp exited with code 0
```

In addition, I believe there is a missing port to call from the outside.
